apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-env
  annotations:
    policies.kyverno.io/title: Add an env
    policies.kyverno.io/category: Sample
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Label
    policies.kyverno.io/description: >-
      This sample policy adds an environment variable to specific container.
spec:
  rules:
  - name: add-env
    match:
      resources:
        kinds:
        - Pod
    mutate:
      patchStrategicMerge:
        spec:
          containers:
            - name: alpine
              env:
                - name: NEWVAR
                  value: NEWVAL
