apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      env:
        - name: VAR1
          value: VAL1
        - name: VAR2
          value: VAL2
    - name: alpine
      image: alpine
      env:
        - name: VAR1
          value: VAL1
        - name: VAR2
          value: VAL2
